spring:
  application:
    name: klage-kodeverk-api
  main:
    banner-mode: OFF

management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 7081
  error:
    whitelabel:
      enabled: false
  shutdown: graceful


